### PR TITLE
Remove moment.js dependency and fix UTC time string conversion to local time date object

### LINKED ISSUE #7: Time not correctly parsing UTC
When i make a raw call using curl to:
`https://bittrex.com/api/v1.1/public/getmarkethistory?market=USDT-BTC`

I get the following:

```
{
    "success": true,
    "message": "",
    "result": [
        {
            "Id": 31205548,
            "TimeStamp": "2017-12-18T03:52:51.587",
            "Quantity": 0.00331552,
            "Price": 18473,
            "Total": 61.24760096,
            "FillType": "FILL",
            "OrderType": "BUY"
        },
        {
            "Id": 31205547,
            "TimeStamp": "2017-12-18T03:52:51.587",
            "Quantity": 0.00259669,
            "Price": 18470,
            "Total": 47.9608643,
            "FillType": "PARTIAL_FILL",
            "OrderType": "BUY"
        }...
```

However, when i look at the data coming back from:

```
this.bittrex.marketHistory(markets);
```

It's converting the dates into a different timezone.

```
2017-12-18T08:52:40.997Z
2017-12-18T08:52:40.997Z
2017-12-18T08:52:40.997Z
2017-12-18T08:52:40.997Z
2017-12-18T08:52:40.997Z
2017-12-18T08:52:38.840Z
2017-12-18T08:52:38.840Z
2017-12-18T08:52:37.120Z
2017-12-18T08:52:27.963Z
2017-12-18T08:52:22.260Z
2017-12-18T08:52:20.150Z
```

Given that `3:52:51.587` is UTC time and `10:52:51.587` is Local Time, when i call marketHistory, then it should be represented either in pure UTC or Local Time.

### PR DESCRIPTION
**Pull request by harry-sm**
Fix #7

### CODE REVIEW

**Comment by harry-sm** [comment]
@lookfirst 

So sorry I didn't run a build.

**Comment by lookfirst** [comment]
Weird, I don't see the change to the `.ts` file.

**Comment by harry-sm** [comment]
Not sure what happened but i just made the changes should be good now.

**Comment by lookfirst** [comment]
@harry-sm thanks man!

**Comment by harry-sm** [comment]
@lookfirst 
No problem.

**Pull request merged**
